# refer https://hub.docker.com/_/postgres/

version: '3.1'

services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    restart: always
